/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentTypeSelector: typeof import('./components/chat/AgentTypeSelector.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppLogo: typeof import('./components/common/AppLogo.vue')['default']
    AppNavbar: typeof import('./components/layout/AppNavbar.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ChatBubble: typeof import('./components/chat/ChatBubble.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ChatMessageList: typeof import('./components/chat/ChatMessageList.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    ErrorState: typeof import('./components/common/ErrorState.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    MarkdownRenderer: typeof import('./components/common/MarkdownRenderer.vue')['default']
    PageTransition: typeof import('./components/common/PageTransition.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionListItem: typeof import('./components/chat/SessionListItem.vue')['default']
    SidebarMenu: typeof import('./components/layout/SidebarMenu.vue')['default']
    StreamingBubble: typeof import('./components/chat/StreamingBubble.vue')['default']
    TokenUsageBadge: typeof import('./components/chat/TokenUsageBadge.vue')['default']
    UserAvatar: typeof import('./components/common/UserAvatar.vue')['default']
    UserDropdown: typeof import('./components/layout/UserDropdown.vue')['default']
  }
}
