FROM node:20-bookworm AS builder

WORKDIR /build

COPY frontend/package*.json ./

RUN npm install --include=dev --legacy-peer-deps

COPY frontend/ ./

RUN npm run build

FROM nginx:1.27-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /build/dist /usr/share/nginx/html

COPY env/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]